os: [linux]
sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
env:
  - ROOT_VERSION=6.06.02
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-dev
      - libboost-log1.55-dev
      - graphviz
before_install:
  - ./travis/decrypt_key.sh 
  - pip install --user cpp-coveralls
install:
  - export CXX=g++-4.9
  - export CC=gcc-4.9
  - source travis/get-cmake.sh
  - source travis/get-root.sh
  - source travis/get-lhapdf.sh
  - source travis/get-doxygen.sh
before_script:
  - export CXX=g++-4.9
  - export CC=gcc-4.9
  - mkdir build
  - cd build
  - cmake .. -DTESTS=ON -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug
script:
  - make -j2 && ./tests/unit_tests/unit_tests.exe
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then coveralls -e 'external/' --gcov-options '\-lp' -E '.*CMakeCXXCompilerId\.cpp' -E '.*CMakeCCompilerId\.c' -E '.*feature_tests\.c.*' -r .. &> /dev/null; fi
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then ./make_docs.sh; fi
